### ISSUE TITLE
Deprecation error on PHP 8.1

### ISSUE THREAD

**Issue by witschko** [TheBnl/silverstripe-cookie-consent#47] opened 2022-09-12 07:38 UTC
Hi,

I just got the following error in `bramdeleeuw/cookieconsent/src/CookieConsent.php` when running on PHP 8.1:

```
[Deprecated] explode(): Passing null to parameter #2 ($string) of type string is deprecated
GET /server-error/
Line 123 in /usr/src/myapp/vendor/bramdeleeuw/cookieconsent/src/CookieConsent.php
```

It seems `Cookie::get(CookieConsent::COOKIE_NAME)` return null which is no longer allowed.

**Comment by TheBnl** [comment] 2022-10-26 08:37
Hi Philipp, the issue is fixed by @josephlewisnz i'll tag a new release so you can update to php 8.1

**Closed as completed by TheBnl** 2022-10-26 08:37 UTC
